"""add user profile fields

Revision ID: 97cb417ae8a5
Revises: 8de0c529cba5
Create Date: 2026-04-29 16:40:49.866773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97cb417ae8a5'
down_revision: Union[str, Sequence[str], None] = '8de0c529cba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('priority', sa.Enum('low', 'medium', 'high', name='priority_enum'), nullable=True))
    op.add_column('todos', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('todos', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('todos_owner_id_fkey'), 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('todos', 'createdAt')
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'address')
    op.drop_column('users', 'age')
    op.drop_column('users', 'gender')
    op.add_column('todos', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key(op.f('todos_owner_id_fkey'), 'todos', 'users', ['owner_id'], ['id'])
    op.drop_column('todos', 'created_at')
    op.drop_column('todos', 'due_date')
    op.drop_column('todos', 'priority')
    # ### end Alembic commands ###
